-- MySQL Script generated by MySQL Workbench
-- Fri Jun 26 13:24:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema coucoudb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coucoudb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coucoudb` DEFAULT CHARACTER SET utf8 ;
USE `coucoudb`;

-- -----------------------------------------------------
-- Table `coucoudb`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coucoudb`.`locations`(
  `lc_id` INT NOT NULL,
  `lc_name` VARCHAR(255) NOT NULL,
  `lc_type` VARCHAR(1) NOT NULL,
  `location_id` INT NULL,
  PRIMARY KEY (`lc_id`),
  CONSTRAINT `fk_locations_locations`
    FOREIGN KEY (`location_id`)
    REFERENCES `coucoudb`.`locations` (`lc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_locations_locations_idx` ON locations (`location_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`shops`
-- -----------------------------------------------------
CREATE TABLE shops(
  `sh_id` INT NOT NULL AUTO_INCREMENT,
  `lc_id` INT NOT NULL,
  `sh_nit` VARCHAR(100) NOT NULL,
  `sh_name` VARCHAR(45) NOT NULL,
  `sh_address` VARCHAR(45) NOT NULL,
  `sh_email` VARCHAR(100) NOT NULL,
  `sh_phone` VARCHAR(30) NOT NULL,
  `sh_lat` FLOAT NOT NULL,
  `sh_lng` FLOAT NOT NULL,
  `sh_photo` TEXT NOT NULL,
  `sh_created` DATETIME NOT NULL,
  PRIMARY KEY (`sh_id`),
  CONSTRAINT `fk_shops_locations1`
    FOREIGN KEY (`lc_id`)
    REFERENCES `coucoudb`.`locations` (`lc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_shops_locations1_idx` ON shops (`lc_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`type_products`
-- -----------------------------------------------------
CREATE TABLE type_products(
  `tp_id` INT NOT NULL AUTO_INCREMENT,
  `tp_name` VARCHAR(45) NOT NULL,
  `tp_photo` TEXT NOT NULL,
  PRIMARY KEY (`tp_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`measures`
-- -----------------------------------------------------
CREATE TABLE measures(
  `me_id` INT NOT NULL AUTO_INCREMENT,
  `me_name` VARCHAR(45) NOT NULL COMMENT 'ml, L, gr, kg',
  PRIMARY KEY (`me_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`products`
-- -----------------------------------------------------
CREATE TABLE products(
  `pr_id` INT NOT NULL AUTO_INCREMENT,
  `tp_id` INT NOT NULL,
  `pr_code` VARCHAR(45) NOT NULL,
  `pr_name` VARCHAR(45) NOT NULL,
  `pr_net_weight` INT NOT NULL COMMENT '100, 200, 165',
  `me_id` INT NOT NULL,
  `pr_iva` INT NOT NULL COMMENT '5, 19',
  `pr_photo` TEXT NOT NULL,
  PRIMARY KEY (`pr_id`),
  CONSTRAINT `fk_products_type_products`
    FOREIGN KEY (`tp_id`)
    REFERENCES `coucoudb`.`type_products` (`tp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_measures1`
    FOREIGN KEY (`me_id`)
    REFERENCES `coucoudb`.`measures` (`me_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_products_type_products_idx` ON products (`tp_id` ASC) VISIBLE;

CREATE INDEX `fk_products_measures1_idx` ON products (`me_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`users`
-- -----------------------------------------------------
CREATE TABLE users(
  `us_id` INT NOT NULL AUTO_INCREMENT,
  `us_username` VARCHAR(100) NOT NULL,
  `us_password` TEXT NOT NULL,
  `us_name` VARCHAR(45) NOT NULL,
  `us_lastname` VARCHAR(45) NOT NULL,
  `us_identification` BIGINT NOT NULL,
  `us_gender` VARCHAR(1) NOT NULL COMMENT 'F, (Femenino)\nM, (Masculino)',
  `us_photo` TEXT NOT NULL,
  `us_created` DATETIME NOT NULL,
  PRIMARY KEY (`us_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`roles`
-- -----------------------------------------------------
CREATE TABLE roles(
  `ro_id` INT NOT NULL AUTO_INCREMENT,
  `ro_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ro_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`shops_roles`
-- -----------------------------------------------------
CREATE TABLE shops_roles(
  `sr_id` INT NOT NULL AUTO_INCREMENT,
  `sh_id` INT NOT NULL,
  `us_id` INT NOT NULL,
  `ro_id` INT NOT NULL,
  `sr_code` VARCHAR(45) NOT NULL,
  `sr_state` VARCHAR(1) NOT NULL DEFAULT 'A',
  `sr_created` DATETIME NOT NULL,
  PRIMARY KEY (`sr_id`),
  CONSTRAINT `fk_users_shops_users1`
    FOREIGN KEY (`us_id`)
    REFERENCES `coucoudb`.`users` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_shops_shops1`
    FOREIGN KEY (`sh_id`)
    REFERENCES `coucoudb`.`shops` (`sh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_shops_roles1`
    FOREIGN KEY (`ro_id`)
    REFERENCES `coucoudb`.`roles` (`ro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_users_shops_users1_idx` ON shops_roles (`us_id` ASC) VISIBLE;

CREATE INDEX `fk_users_shops_shops1_idx` ON shops_roles (`sh_id` ASC) VISIBLE;

CREATE INDEX `fk_users_shops_roles1_idx` ON shops_roles (`ro_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`type_client`
-- -----------------------------------------------------
CREATE TABLE type_client(
  `tc_id` INT NOT NULL AUTO_INCREMENT,
  `tc_name` VARCHAR(45) NOT NULL COMMENT 'DN, (Distribuidor persona natural)\nDJ, (Distribuidor persona jurídica)\nCN, (Cliente persona natural)\nCJ, (Cliente persona jurídica)\nCC, (Cliente común)',
  PRIMARY KEY (`tc_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`clients`
-- -----------------------------------------------------
CREATE TABLE clients(
  `cl_id` INT NOT NULL AUTO_INCREMENT,
  `tc_id` INT NOT NULL,
  `cl_nit` VARCHAR(100) NOT NULL,
  `cl_name` VARCHAR(45) NOT NULL,
  `cl_address` VARCHAR(200) NOT NULL,
  `cl_email` VARCHAR(100) NOT NULL,
  `cl_phone` VARCHAR(45) NOT NULL,
  `cl_username` VARCHAR(100) NULL,
  `cl_password` TEXT NULL,
  `cl_created` DATETIME NOT NULL,
  PRIMARY KEY (`cl_id`),
  CONSTRAINT `fk_clients_type_client1`
    FOREIGN KEY (`tc_id`)
    REFERENCES `coucoudb`.`type_client` (`tc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_clients_type_client1_idx` ON clients (`tc_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`invoices`
-- -----------------------------------------------------
CREATE TABLE invoices(
  `in_id` INT NOT NULL AUTO_INCREMENT,
  `sh_id` INT NOT NULL,
  `sr_id` INT NOT NULL,
  `cl_id` INT NOT NULL,
  `in_serial_dian` VARCHAR(500) NULL,
  `in_serial_shop` VARCHAR(500) NULL,
  `in_type` VARCHAR(1) NOT NULL COMMENT 'D, (Distributor)\nC, (Client)',
  `in_total_client` DECIMAL NOT NULL,
  `in_total_distributor` DECIMAL NOT NULL,
  `in_date` DATE NOT NULL,
  `in_hour` TIME NOT NULL,
  PRIMARY KEY (`in_id`),
  CONSTRAINT `fk_invoices_shops1`
    FOREIGN KEY (`sh_id`)
    REFERENCES `coucoudb`.`shops` (`sh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoices_shops_roles1`
    FOREIGN KEY (`sr_id`)
    REFERENCES `coucoudb`.`shops_roles` (`sr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoices_clients1`
    FOREIGN KEY (`cl_id`)
    REFERENCES `coucoudb`.`clients` (`cl_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_invoices_shops1_idx` ON invoices (`sh_id` ASC) VISIBLE;

CREATE INDEX `fk_invoices_shops_roles1_idx` ON invoices (`sr_id` ASC) VISIBLE;

CREATE INDEX `fk_invoices_clients1_idx` ON invoices (`cl_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`shops_products`
-- -----------------------------------------------------
CREATE TABLE shops_products(
  `sp_id` INT NOT NULL AUTO_INCREMENT,
  `sh_id` INT NOT NULL,
  `pr_id` INT NOT NULL,
  `sp_value_client` DECIMAL NOT NULL,
  `sp_value_distributor` DECIMAL NOT NULL,
  `sp_stock` INT NOT NULL,
  `sp_state` VARCHAR(1) NOT NULL DEFAULT 'A',
  `sp_created` DATETIME NOT NULL,
  PRIMARY KEY (`sp_id`),
  CONSTRAINT `fk_shops_products_shops1`
    FOREIGN KEY (`sh_id`)
    REFERENCES `coucoudb`.`shops` (`sh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shops_products_products1`
    FOREIGN KEY (`pr_id`)
    REFERENCES `coucoudb`.`products` (`pr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_shops_products_shops1_idx` ON shops_products (`sh_id` ASC) VISIBLE;

CREATE INDEX `fk_shops_products_products1_idx` ON shops_products (`pr_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`sales`
-- -----------------------------------------------------
CREATE TABLE sales(
  `sa_id` INT NOT NULL AUTO_INCREMENT,
  `in_id` INT NOT NULL,
  `sp_id` INT NOT NULL,
  `sa_quantity` INT NOT NULL,
  `sa_discount` DECIMAL NOT NULL COMMENT '0 (0%), 0.5 (50%), 1 (100%)',
  `sa_subtotal_client` DECIMAL NOT NULL,
  `sa_subtotal_distributor` DECIMAL NOT NULL,
  `sa_created` DATETIME NOT NULL,
  PRIMARY KEY (`sa_id`),
  CONSTRAINT `fk_sales_purchases_invoices1`
    FOREIGN KEY (`in_id`)
    REFERENCES `coucoudb`.`invoices` (`in_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_shops_products1`
    FOREIGN KEY (`sp_id`)
    REFERENCES `coucoudb`.`shops_products` (`sp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_sales_purchases_invoices1_idx` ON sales (`in_id` ASC) VISIBLE;

CREATE INDEX `fk_sales_shops_products1_idx` ON sales (`sp_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`type_supplies`
-- -----------------------------------------------------
CREATE TABLE type_supplies(
  `ts_id` INT NOT NULL AUTO_INCREMENT,
  `ts_name` VARCHAR(45) NOT NULL,
  `ts_photo` TEXT NOT NULL,
  PRIMARY KEY (`ts_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `coucoudb`.`supplies`
-- -----------------------------------------------------
CREATE TABLE supplies(
  `su_id` INT NOT NULL AUTO_INCREMENT,
  `ts_id` INT NOT NULL,
  `su_code` VARCHAR(45) NOT NULL,
  `su_name` VARCHAR(200) NOT NULL,
  `me_id` INT NOT NULL,
  `su_description` VARCHAR(500) NOT NULL,
  `su_photo` TEXT NOT NULL,
  PRIMARY KEY (`su_id`),
  CONSTRAINT `fk_supplies_type_supplies1`
    FOREIGN KEY (`ts_id`)
    REFERENCES `coucoudb`.`type_supplies` (`ts_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_supplies_measures1`
    FOREIGN KEY (`me_id`)
    REFERENCES `coucoudb`.`measures` (`me_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_supplies_type_supplies1_idx` ON supplies (`ts_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`shops_supplies`
-- -----------------------------------------------------
CREATE TABLE shops_supplies(
  `ss_id` INT NOT NULL AUTO_INCREMENT,
  `sh_id` INT NOT NULL,
  `su_id` INT NOT NULL,
  `ss_value` DECIMAL NOT NULL,
  `ss_stock` INT NOT NULL,
  `ss_state` VARCHAR(1) NOT NULL DEFAULT 'A',
  `ss_created` DATETIME NULL,
  PRIMARY KEY (`ss_id`),
  CONSTRAINT `fk_shops_supplies_shops1`
    FOREIGN KEY (`sh_id`)
    REFERENCES `coucoudb`.`shops` (`sh_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shops_supplies_supplies1`
    FOREIGN KEY (`su_id`)
    REFERENCES `coucoudb`.`supplies` (`su_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_shops_supplies_shops1_idx` ON shops_supplies (`sh_id` ASC) VISIBLE;

CREATE INDEX `fk_shops_supplies_supplies1_idx` ON shops_supplies (`su_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`supplies_products`
-- -----------------------------------------------------
CREATE TABLE supplies_products(
  `su_id` INT NOT NULL,
  `pr_id` INT NOT NULL,
  CONSTRAINT `fk_supplies_products_supplies1`
    FOREIGN KEY (`su_id`)
    REFERENCES `coucoudb`.`supplies` (`su_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_supplies_products_products1`
    FOREIGN KEY (`pr_id`)
    REFERENCES `coucoudb`.`products` (`pr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_supplies_products_supplies1_idx` ON supplies_products (`su_id` ASC) VISIBLE;

CREATE INDEX `fk_supplies_products_products1_idx` ON supplies_products (`pr_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `coucoudb`.`orden_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coucoudb`.`orden_cards` (
  `oc_id` INT NOT NULL AUTO_INCREMENT,
  `us_id` INT NOT NULL,
  `table` INT NOT NULL,
  `oc_state` VARCHAR(1) NOT NULL DEFAULT 'A',
  `oc_created` DATETIME NOT NULL,
  PRIMARY KEY (`oc_id`),
  CONSTRAINT `fk_orden_cards_users`
    FOREIGN KEY (`us_id`)
    REFERENCES `coucoudb`.`users` (`us_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_orden_cards_users_idx` ON `coucoudb`.`orden_cards` (`us_id` ASC) VISIBLE;

-- -----------------------------------------------------
-- Table `coucoudb`.`ordens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coucoudb`.`ordens` (
  `or_id` INT NOT NULL AUTO_INCREMENT,
  `oc_id` INT NOT NULL,
  `sp_id` INT NOT NULL,
  `or_stock` INT NOT NULL,
  PRIMARY KEY (`or_id`),
  CONSTRAINT `fk_ordens_orden_cards1`
    FOREIGN KEY (`oc_id`)
    REFERENCES `coucoudb`.`orden_cards` (`oc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordens_shops_products1`
    FOREIGN KEY (`sp_id`)
    REFERENCES `coucoudb`.`shops_products` (`sp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_ordens_orden_cards1_idx` ON `coucoudb`.`sales` (`oc_id` ASC) VISIBLE;

CREATE INDEX `fk_ordens_shops_products1_idx` ON `coucoudb`.`sales` (`sp_id` ASC) VISIBLE;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
